name: Build Flet APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Libraries
        run: pip install -r requirements.txt

      - name: Build APK
        run: echo "y" | flet build apk --project teacher_match --product "Teacher Match" --org com.agency.teachermatch --include-packages flet_file_picker
        
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-app-apk
          path: build/apk/**/*.apk