name: Build Flet APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # ဤနေရာတွင် Flet မှ တရားဝင်ထုတ်ပေးထားသော အသင့်သုံးစနစ် (Container) ကို အသုံးပြုထားပါသည်
    container:
      image: ghcr.io/flet-dev/flet-build:main

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Install Libraries
        run: pip install -r requirements.txt --break-system-packages || pip install -r requirements.txt

      - name: Build APK
        # Container ထဲတွင် အားလုံး အသင့်ရှိနေပြီဖြစ်၍ ရိုးရှင်းစွာ Run ရုံသာ ဖြစ်ပါသည်
        run: flet build apk --project teacher_match --product "Teacher Match" --org com.agency.teachermatch

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-app-apk
          path: build/apk/**/*.apk